apiVersion: v1
kind: Service
metadata:
  name: node-microservice-template
spec:
  selector:
    app: node-microservice-template
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
